.\" Manpage for Impulse.
.\" Contact jake@jr0.org to correct errors or typos.
.TH man 8 "17 Apr 2020" "1.0" "impulse man page"
.SH NAME
impulse \- a simple package manager 
.SH SYNOPSIS
impulse [OPTION]... [PACKAGE NAME]...
.SH DESCRIPTION
A simple package manager
.SH OPTIONS
-U	Update package list
.br
-S	Download file by name
.br
-Ss	Search file by name or "a" to list all files
.SH BUG
if flags are not passed to rushnote, rushnote errors out and closes
.SH AUTHOR
Jake Roggenbuck, jake@jr0.org
