#!/usr/bin/env python3

from subprocess import check_output
from termcolor import colored
from pathlib import Path
import requests
import hashlib
import yaml
import json
import sys


with open(f'{str(Path.home())}/.config/impulse/config.yaml') as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

def download_file(url, path, dohash):
    local_filename = url.split('/')[-1]
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        sha = hashlib.sha256()
        with open(f'{path}{local_filename}', 'wb+') as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
                    sha.update(chunk)
        if dohash:
            print(sha.hexdigest())
    
    return local_filename


def download_package(url, name, dohash): 
    print(f"Downloading {name} from {url}")
    download_file(f"{url}{name}.tar.gz", "/tmp/", True)
    print(colored(f"Done downloading {name}", 'green'))


def download_list(url): 
    print(f"Downloading list from {url}")
    download_file(f"{url}list.json", f'{str(Path.home())}{config["local_path"]}', False)
    print(colored("Done downloading list", 'green'))


def search_list(term):
    with open(f"{str(Path.home())}{config['local_path']}list.json") as json_file:
        data = json.load(json_file)
        if term in data:
            print(data[term]["name"])
            print(f'-- {data[term]["desc"]}')


if sys.argv[1] == "-U":
   download_list(config["upstream"]) 

if sys.argv[1] == "-S":
    download_package(config["upstream"], sys.argv[2], True)

if sys.argv[1] == "-Ss":
    search_list(sys.argv[2])

